USE [master]
GO

/****** Object:  Database [MittoSMS]    Script Date: 1/20/2018 8:59:02 PM ******/
CREATE DATABASE [MittoSMS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MittoSMS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\MittoSMS.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'MittoSMS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\MittoSMS_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [MittoSMS] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MittoSMS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MittoSMS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MittoSMS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MittoSMS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MittoSMS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MittoSMS] SET ARITHABORT OFF 
GO

ALTER DATABASE [MittoSMS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MittoSMS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MittoSMS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MittoSMS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MittoSMS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MittoSMS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MittoSMS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MittoSMS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MittoSMS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MittoSMS] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MittoSMS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MittoSMS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MittoSMS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MittoSMS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MittoSMS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MittoSMS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MittoSMS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MittoSMS] SET RECOVERY FULL 
GO

ALTER DATABASE [MittoSMS] SET  MULTI_USER 
GO

ALTER DATABASE [MittoSMS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MittoSMS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MittoSMS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MittoSMS] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [MittoSMS] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MittoSMS] SET  READ_WRITE 
GO


